#!/usr/bin/env python
"""
data_io based speechbrain

Adopted from speechbrain.core

"""
from __future__ import absolute_import

import os
import sys
from pathlib import Path

import core_scripts.data_io.io_tools as nii_io_tk
import core_scripts.data_io.seq_info as nii_seqinfo

import speechbrain as sb
from speechbrain.dataio.sampler import ReproducibleRandomSampler

class SBDatasetWrapper:
    """SBDatasetWrapper(dataset, flag_train, loader_kwargs)

    This is a wrapper over speechbrain dataset.
    It should be compatible with the training/inference scripts in nn_wrappper.

    Args
    ----
      dataset:        speechbrain dataset object
      flag_train:     bool, whether this is in training mode or not
      loader_kwargs:  kwargs used for speechbrain dataloader
                      for example, in hyaml
      f_save_item:    a function to save data in a specified format
                      if None, we will use the default method

    Here is one example on loader_kwargs:
    dataloader_eval_options:
        batch_size: 1
        shuffle: False
        num_workers: !ref <num_workers>
        collate_fn: !name:core_scripts.data_io.sb_collate.PaddedBatch_customize
    """
    def __init__(self, dataset, flag_train, loader_kwargs, f_save_item = None):
        
        # link dataset
        self.dataset = dataset

        # flag
        self.flag_train = flag_train

        # create data loader
        self.data_loader = make_dataloader(dataset, flag_train, **loader_kwargs)

        # name tagger
        self.db_type = 'speechbrain'

        # method to save data
        if f_save_item is None:
            self.f_save_item = f_sb_default_putitem
        else:
            self.f_save_item = f_save_item 
        return
        
    def print_info(self):
        """print_info(self)
        Print basic information about the dataset.
        Since no pre-check is done on the data, we don't know the statics.
        Just show the number of data samples here.
        """
        mes = "Dataset using speechbrain dataset IO"
        mes += "\n  Number of data samples: {:d}".format(self.get_seq_num())
        print(mes)
        return

    def get_loader(self):
        """dataloader = get_loader()
        return a data loader
        """
        return self.data_loader
    
    def get_seq_num(self):
        """seq_num = get_seq_num()
        return the number of data sample (sequences) in the dataset
        """
        return len(self.dataset.data)

    def putitem(self, data_gen, save_dir, name_prefix, seq_info):
        """putitem(data_gen, save_dir, name, seq_info)
        save data_gen into a specified format at a specified place
        
        This is to simulat the behavior of f_putitem in default_data_io.
        This will be called in nn_manager.py.f_inference_wrapper_sb to save
        the output generated by a model.
        """
        # read the sentence information
        tmp_seq_info = nii_seqinfo.SeqInfo()
        tmp_seq_info.parse_from_str(seq_info)

        # write the data
        file_name = tmp_seq_info.seq_tag()
        file_name = name_prefix + file_name 
        
        # create the parent directory if necessary
        file_path = Path(save_dir) / file_name
        file_path.parent.mkdir(parents=True, exist_ok=True)

        self.f_save_item(data_gen, file_path)
        return


# ==========================
# functions adopted from default_data_io
# ==========================
def f_sb_default_putitem(output_data, file_path):
    """f_sb_default_putitem(output_data, save_dir, filename_prefix, data_infor)
    
    This default putitem simply save output data as *.bin in the save_dir
    input
    -----
      output_data:      torch tensor, any shape
      file_path:        str or Path, path to save the file
    """
    # save using the default IO as binary data
    nii_io_tk.f_write_raw_mat(output_data.numpy(),file_path.with_suffix('.bin'))
    return


# ==========================
# functions from speechbrain
# ==========================

def make_dataloader(dataset, flag_train, **loader_kwargs):
    """Creates DataLoaders for Datasets.
    
        This is used by ``fit()`` and ``evaluate()`` if they just receive
        Datasets.

        Alternatively, this can be called from outside the Brain subclass.
        In that case, the DataLoader should be passed to ``fit()`` in place
        of the dataset.

        The Stage.TRAIN DataLoader is handled specially. It has extra args for
        shuffle and drop_last. In DDP a DistributedSampler is created (unless
        the dataset is an IterableDataset).

        NOTE
        ----
        Some important DataLoader arguments are passed via **loader_kwargs,
        e.g., batch_size, num_workers, pin_memory.

        NOTE
        ----
        By default, ``evaluate()`` specifies ckpt_prefix=None to stop the test
        DataLoader being added to the checkpointer. If you need to add a
        recoverable after saving checkpoints (e.g., at test time, after
        checkpointing the training), and still be able to recover reasonably,
        you should probably specify ``allow_partial_load=True``.

        Arguments
        ---------
        dataset : Dataset
            A set of data to use to create data loader. If the Dataset is a
            DynamicItemDataset, PaddedBatch is used as the default collate_fn,
            unless specified in loader_kwargs.
        stage : Stage
            The stage of the experiment: Stage.TRAIN, Stage.VALID, Stage.TEST
        ckpt_prefix : str, None
            Prefix to use for SaveableDataLoader Checkpoint name. The Stage
            name is added to this to create the full key. Set to None to not
            save the DataLoader.
        **loader_kwargs : dict
            Additional keyword arguments to the DataLoader.
            E.g., batch_size, num_workers, pin_memory.
    """
    # TRAIN stage is handled specially.
    if flag_train:
        loader_kwargs = _train_loader_specifics(dataset, loader_kwargs)
    # This commented-out code block is useful when one can ensure
    # metric reporting is DDP-valid for VALID & EVAL datasets.
    # elif self.distributed_launch:
    #     loader_kwargs = sb.dataio.dataloader.distributed_loader_specifics(
    #         self.distributed_launch, self.rank, dataset, loader_kwargs
    #     )
    dataloader = sb.dataio.dataloader.make_dataloader(
        dataset, **loader_kwargs
    )

    return dataloader

def _train_loader_specifics(dataset, loader_kwargs):
    sampler = loader_kwargs.get("sampler", None)
    # Shuffling should really only matter for the train stage. Shuffling
    # will also lead to more padding in batches if the order was otherwise
    # sorted by length.
    shuffle = loader_kwargs.get("shuffle", False)
    if shuffle:
        if sampler is not None:
            raise ValueError(
                "Cannot specify both shuffle=True"
                "and a sampler in loader_kwargs"
            )
        sampler = ReproducibleRandomSampler(dataset)
        train_sampler = sampler
        loader_kwargs["sampler"] = train_sampler
        # Delete the shuffle flag, since you cannot specify both a sampler and
        # shuffling:
        del loader_kwargs["shuffle"]
    return loader_kwargs



if __name__ == "__main__":
    print(__doc__)
